language: cpp

compiler: gcc

sudo: required
dist: trusty

os:
  - linux
  # - osx

before_install:
  - ./.travis.sh "before_install"

install:
  - ./.travis.sh "install"

before_script:
  - ./.travis.sh "before_script"

script:
  - ./.travis.sh "script"

before_deploy:
  - ./.travis.sh "before_deploy"

deploy:
  provider: releases
  api_key:
    secure: JQ6ecaKC7t6g8QD/vn0h/vJij9FlaTtmpK18Osgu0BX5vdPPAwgLoAjz5pqcO6BZnctkZkM7Ttrklnubh36pEuqdR6SzGyXHT8bylkU1g+8ZybIkKv7pia/QMJ8F8vzD63h0b5gnmFIzaBeYdszEeVc6q3DjcgLLYHG65ry/wCcleZw+xTZy3lR3N/4haJkKRDZRcnB5EwRjLYi1EyxfiunRfQ/DWxxY3jQJQCugQJ8J6FG92QhalBRTHAxMF22cvhvoUWKMmZ/qgpOpT2hyVLAjF1dRlquv7JA3wAzDamNGFaf88UBODX0u8rFjnk/Gq90zN69pKxj5oRBsQeLSLlr9wm6+99l5jOy/2LdTqSvWfQI3yOODAtqGK3OcQPF0j2+uPs9WUxzkEzVL+ittgq0I3Dg3Sv71m5i7ahvZDut6X6U7Qrx0QRvczAyZ6QgGNn8HXPWfQzW/2tQ23Hdqu/El6h1ZLKPyzXoh9tbbszul7r5LDIAuxCvN5gO0p+CyB3JzPsWz5/CzVyQTLrufpkRAwGGebOR9FYhPqTCLrAIFDtDk/qEO76R64ZJ9Dw9tqK6Luq4UwlJ+LEUWtQdaeOXTTMpJxzPVTIsijlqqSQz9mwaN5MkwtnZPpIuF6TBu66DJi1hgzwpRfZrxV6DUoeJy5VMqG/qHxQ7Ez2XWq4M=
  file: "${TRAVIS_OS_NAME}.zip"
  skip_cleanup: true
  on:
    tags: true
    repo: maek/unrealarena-deps
